### ISSUE TITLE
Suggestions for web-app integrations

### ISSUE THREAD

**Issue by babineaum** [DataDog/hiring-engineers#18]
Hi Dev Gurus,

I am doing the Solutions Engineer hiring challenge and was wondering if you have an suggestions as to a good example of a web-app to integrate in. I have used a few apps but can't really think of something small enough that wouldn't be too complicated while trying to get things running. I ran across Plone (plone.org) and I am thinking of using it but figured I would reach out to see if you had anything in mind. Thanks! 

Matt Babineau

**Comment by ckelner** [comment]
Outdated Q -- Sorry Matt! Closing.
