### ISSUE TITLE
API parser won't accept json of a graph query that is same as json of same graph query in a working timeboard

### ISSUE THREAD

**Issue by michaelcolby** [DataDog/hiring-engineers#397]
{"errors": ["Error(s) found in query:\nError parsing query: \n unable to parse 
    anomalies(avg:mongodb.mem.resident{host:colby-exercise-machine.localdomain}, basic, 2): Rule 
    'scope_expr' didn't match at ', 2)' (line 1, column 83)."]}  

submitting the json for the timeboard via curl results in this error above, for specifically the one query that utilizes basic anomaly detection, the 3rd graph.

    	curl  -X POST -H "Content-type: application/json" \
	-d '{
		  "graphs" : [{
			  "title": "Avg of my_metric over host:colby-exercise-machine.localdomain",
			  "definition": {
				  "events": [],
				  "requests": [
					  {"q": "avg:my_metric{host:colby-exercise-machine.localdomain}"}
				  ]
			  },
			  "viz": "timeseries"
		  },
		  {
			  "title": "my_metric with 3600 second rollup",
			  "definition": {
				  "events": [],
				  "requests": [
					  {"q": "avg:my_metric{*} by {role}.rollup(sum, 3600)",
									"aggregator": "avg}"}
				  ]
			  },
			  "viz": "timeseries"
			  },
		  {
			  "title": "Avg of mongodb.mem.resident over host:colby-exercise-machine.localdomain",
			  "definition": {
				  "events": [],
				  "requests": [
					  {"q": "anomalies(avg:mongodb.mem.resident{host:colby-exercise-machine.localdomain}, 'basic', 2)",
									"aggregator": "avg"}
				  ]
			  },
			  "viz": "timeseries"

		  }],

Evidence of it working graph created in the Datadog GUI

![anomaly-gui-definition](https://user-images.githubusercontent.com/36873008/40384039-46257d86-5db7-11e8-8b17-889faa9aeac3.jpg)
![anamoly-gui-json](https://user-images.githubusercontent.com/36873008/40384040-4643e4b0-5db7-11e8-8a76-a26d393b0a2b.jpg)

**Comment by ToddRizley** [comment]
Hi there -- we are unable to help troubleshoot on the hiring challenge nor give feedback. Please reach out to the recruiter you are working with if you are having issues.
