### ISSUE TITLE
APM reports service seen on client machine but nothing reported on Datadog SAAS

### ISSUE THREAD

**Issue by michaelcolby** [DataDog/hiring-engineers#399]
my flask app (apmtest.py) is running, invoked with ddtrace and ddtrace.api appears to have recognized 1 service. But i'm not seeing a service reported to APM on Datadog GUI

	ddtrace-run python apmtest.py
	DEBUG:ddtrace.contrib.flask.middleware:flask: initializing trace middleware
	2018-05-22 23:46:18,091 - ddtrace.contrib.flask.middleware - DEBUG - flask: initializing trace middleware
	DEBUG:ddtrace.writer:resetting queues. pids(old:None new:111315)
	2018-05-22 23:46:18,092 - ddtrace.writer - DEBUG - resetting queues. pids(old:None new:111315)
	DEBUG:ddtrace.writer:starting flush thread
	2018-05-22 23:46:18,092 - ddtrace.writer - DEBUG - starting flush thread
	 * Serving Flask app "apmtest" (lazy loading)
	 * Environment: production
	   WARNING: Do not use the development server in a production environment.
	   Use a production WSGI server instead.
	 * Debug mode: off
	INFO:werkzeug: * Running on http://127.0.0.1:4999/ (Press CTRL+C to quit)
	2018-05-22 23:46:18,098 - werkzeug - INFO -  * Running on http://127.0.0.1:4999/ (Press CTRL+C to quit)
	DEBUG:ddtrace.api:reported 1 services
	2018-05-22 23:46:19,174 - ddtrace.api - DEBUG - reported 1 services

**With Debug Invoked**

	DATADOG_TRACE_DEBUG=true ddtrace-run python apmtest.py
	DEBUG:ddtrace.commands.ddtrace_run:sys.argv: ['/usr/bin/ddtrace-run', 'python', 'apmtest.py']
	DEBUG:ddtrace.commands.ddtrace_run:ddtrace root: /usr/lib/python2.7/site-packages/ddtrace
	DEBUG:ddtrace.commands.ddtrace_run:ddtrace bootstrap: /usr/lib/python2.7/site-packages/ddtrace/bootstrap
	DEBUG:ddtrace.commands.ddtrace_run:PYTHONPATH: /usr/lib/python2.7/site-packages/ddtrace/bootstrap
	DEBUG:ddtrace.commands.ddtrace_run:sys.path: ['/usr/bin', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages']
	DEBUG:ddtrace.commands.ddtrace_run:program executable: /usr/bin/python
	DEBUG:sitecustomize:skipping malformed patch instruction
	DEBUG:ddtrace.monkey:failed to patch pyramid: module not installed
	DEBUG:ddtrace.monkey:failed to patch aiopg: module not installed
	DEBUG:ddtrace.monkey:failed to patch pymysql: module not installed
	DEBUG:ddtrace.monkey:failed to patch mysqldb: module not installed
	DEBUG:ddtrace.monkey:failed to patch mysql: module not installed
	DEBUG:ddtrace.monkey:failed to patch botocore: module not installed
	DEBUG:ddtrace.monkey:failed to patch cassandra: module not installed
	DEBUG:ddtrace.monkey:failed to patch redis: module not installed
	DEBUG:ddtrace.monkey:failed to patch celery: module not installed
	DEBUG:ddtrace.monkey:failed to patch pylibmc: module not installed
	DEBUG:ddtrace.monkey:failed to patch pymongo: module not installed
	DEBUG:ddtrace.monkey:failed to patch pylons: module not installed
	DEBUG:ddtrace.monkey:failed to patch aiohttp: module not installed
	DEBUG:ddtrace.monkey:failed to patch mongoengine: module not installed
	DEBUG:ddtrace.monkey:failed to patch falcon: module not installed
	DEBUG:ddtrace.monkey:failed to patch psycopg: module not installed
	DEBUG:ddtrace.monkey:failed to patch boto: module not installed
	DEBUG:ddtrace.monkey:failed to patch django: module not installed
	DEBUG:ddtrace.monkey:failed to patch elasticsearch: module not installed
	DEBUG:ddtrace.monkey:failed to patch bottle: module not installed
	INFO:ddtrace.monkey:patched 2/22 modules (flask,sqlite3)
	DEBUG:ddtrace.contrib.flask.middleware:flask: initializing trace middleware
	2018-05-23 14:51:57,317 - ddtrace.contrib.flask.middleware - DEBUG - flask: initializing trace middleware
	DEBUG:ddtrace.tracer:set_service_info: service:flask app:flask type:web
	2018-05-23 14:51:57,317 - ddtrace.tracer - DEBUG - set_service_info: service:flask app:flask type:web
	DEBUG:ddtrace.writer:resetting queues. pids(old:None new:53445)
	2018-05-23 14:51:57,318 - ddtrace.writer - DEBUG - resetting queues. pids(old:None new:53445)
	DEBUG:ddtrace.writer:starting flush thread
	2018-05-23 14:51:57,318 - ddtrace.writer - DEBUG - starting flush thread
	 * Serving Flask app "apmtest" (lazy loading)
	 * Environment: production
	   WARNING: Do not use the development server in a production environment.
	   Use a production WSGI server instead.
	 * Debug mode: off
	INFO:werkzeug: * Running on http://127.0.0.1:80/ (Press CTRL+C to quit)
	2018-05-23 14:51:57,322 - werkzeug - INFO -  * Running on http://127.0.0.1:4999/ (Press CTRL+C to quit)
	DEBUG:ddtrace.api:reported 1 services
	2018-05-23 14:51:58,323 - ddtrace.api - DEBUG - reported 1 services

**Comment by michaelcolby** [comment]
I was able to send APM trace via http with using the API. So I know that sending data to the APM monitor from the agent on my machine is working


	# Create IDs.
	TRACE_ID=($RANDOM % 1000000)
	SPAN_ID=($RANDOM % 1000000)

	# Start a timer.
	START=$(date +%s%N)

	# Do things...
	sleep 2

	# Stop the timer.
	DURATION=$(($(date +%s%N) - $START))

	# Send the traces.
	curl -X PUT -H "Content-type: application/json" \
	  -d "[[{
		\"trace_id\": $TRACE_ID,
		\"span_id\": $SPAN_ID,
		\"name\": \"span_name\",
		\"resource\": \"/home\",
		\"service\": \"service_name\",
		\"type\": \"web\",
		\"start\": $START,
		\"duration\": $DURATION
	}]]" \
	  http://localhost:8126/v0.3/traces



![screen shot 2018-05-23 at 2 38 58 pm](https://user-images.githubusercontent.com/36873008/40452728-b8ef52f2-5e97-11e8-8e9e-1eb320ee7dd2.jpg)

**Comment by michaelcolby** [comment]
use *watch -n* to run the script in timed intervals to generate multiple traces.  
*watch -n 3 ./test-trace.sh*

    watch -n 3 ./test-trace.sh

**Comment by michaelcolby** [comment]
I also tried, using the 


	python apmtestmiddleware.py 
	2018-05-24 23:51:50,171 - ddtrace.contrib.flask.middleware - DEBUG - flask: initializing trace middleware
	2018-05-24 23:51:50,171 - ddtrace.writer - DEBUG - resetting queues. pids(old:None new:27668)
	2018-05-24 23:51:50,171 - ddtrace.writer - DEBUG - starting flush thread
	 * Serving Flask app "apmtestmiddleware" (lazy loading)
	 * Environment: production
	   WARNING: Do not use the development server in a production environment.
	   Use a production WSGI server instead.
	 * Debug mode: off
	2018-05-24 23:51:50,177 - werkzeug - INFO -  * Running on http://192.168.1.129:8126/ (Press CTRL+C to quit)
	2018-05-24 23:51:51,176 - ddtrace.api - DEBUG - reported 1 services

**Comment by michaelcolby** [comment]
more than likely my trial datadog access expired before, turning off accepting APM traces, before i could validate successfully running the flask app, sending results to agent on another machine, is working.

**Comment by ToddRizley** [comment]
Hi there -- we are unable to help troubleshoot on the hiring challenge nor give feedback. Please reach out to the recruiter you are working with if you are having issues.
