### ISSUE TITLE
Get an event to appear in your email inbox?

### ISSUE THREAD

**Issue by jeffslutzky** [DataDog/hiring-engineers#70]
Hi - I seem to be having issues with this. I commented on an event using the @ user format, but nothing is appearing in my inbox. I've tried this several times. I also searched through the API Reference page (http://docs.datadoghq.com/api/) and can't find documentation on another way to do this.

**Comment by DBLaw** [comment]
Jeff,

That's interesting, we'll review this further on our end.

For now you can skip that portion and continue on, no worries.

Thanks for reporting!

Dustin
