### ISSUE TITLE
Datadog agent doesn't use password to connect to MySQL 

### ISSUE THREAD

**Issue by romayankin** [DataDog/hiring-engineers#751]
Hello Datadog team,

My name is Roman Yankin and I have a question for you.

I'm trying to enable integration of MySQL.

I've followed every step in the manual: created user in MySQL for Datadog to connect, granted replication permissions, etc, this is what my C:\ProgramData\Datadog\conf.d\mysql.d\conf.yaml looks like:

`init_config:`

`instances:`
`    # NOTE: Even if the server name is "localhost", the agent will connect to MySQL using TCP/IP, unless you also`
`    # provide a value for the sock key (below).`
`  - server: localhost`
`    user: datadog1`
`    pass: 'q'`

As you can see I'm passing the password for the datadog1 user to authenticate on MySQL server and I can also see that this password works just fine:

`C:\Users\roman>mysql -udatadog1 -pq`
`mysql: [Warning] Using a password on the command line interface can be insecure.`
`Welcome to the MySQL monitor.  Commands end with ; or \g.`
`Your MySQL connection id is 127`
`Server version: 8.0.15 MySQL Community Server - GPL`

`Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.`

`Oracle is a registered trademark of Oracle Corporation and/or its`
`affiliates. Other names may be trademarks of their respective`
`owners.`

`Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.`

`mysql>`

However when I'm looking at the MySQL check inside the Datadog GUI, I see the following:

`mysql (1.5.0)`
`Instance ID: mysql:229398a516bda8d1 [ERROR]`
`Total Runs: 46`
`Metric Samples: 0, Total: 0`
`Events: 0, Total: 0`
`Service Checks: 1, Total: 46`
`Average Execution Time : 3ms`
**Error: (1045, u"Access denied for user 'datadog1'@'localhost' (using password: NO)")**
`Traceback (most recent call last):`

I've tried every possible option to fix the issue including creating additional user for MySQL like this:

CREATE USER 'datadog1'@'127.0.0.1' IDENTIFIED BY 'q';
and even like this:
CREATE USER 'datadog1'@'%' IDENTIFIED BY 'q';

But the error above never went away.

Another observation I have is from the Datadog Agent log file where I found the following entry:

2019-02-11 02:25:45 GMT | ERROR | (runner.go:289 in work) | Error running check mysql: [{"message": "(1045, u\"Access denied for user 'datadog1'@'localhost' (using password: ********

Which apparently is saying that the sctipy is trying to use some password but still can not authenticate.

Are there any hints or suggestions of what might be wrong?

JFYI the version of Phython I'm using is **3.7.2** in case it matters, I've also tried using 2.7.x but to no avail

Thanks,
Roman

**Comment by ToddRizley** [comment]
Hi Roman,
Thanks for reaching out. Unfortunately, given this is a hiring exercise we cannot help to troubleshoot nor can we give any guidance on how to move forward. If you have any issues completing the challenge, I encourage you to reach out to the recruiter you are working with directly.

Thanks,

Todd
